name: Deploy to production based on version tag

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: serverless deploy
        uses: serverless/github-action@master
        with: # https://github.com/serverless/github-action/issues/28
          args: -c "npm install --also=dev && serverless deploy --stage=prod"
          entrypoint: /bin/sh #https://github.com/serverless/github-action/issues/52
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
